<nav class="top-nav__header-menu top-nav__header-menu--noImageButtons">
  <div class="top-nav__main-menu-wrapper top-nav__main-menu-wrapper--noImageButtons">
    <div class="top-nav__menus">
        <p class="top-nav__mobile-title">mainstages:</p>
        <ul class="top-nav__outer-list" id="menu-main-menu">
            <li class="top-nav__item-level-1 first menu-item p-1051">
              <a href="/performances/"> Performances</a>
              <span class="top-nav__submenu-button "><i class="fas fa-plus top-nav__ico-plus"></i><i class="fas fa-minus top-nav__ico-minus"></i></span>
            </li>

            <li class="top-nav__item-level-1 menu-item p-1058">
              <a href="/programming/"> Programming </a>
              <span class="top-nav__submenu-button "><i class="fas fa-plus top-nav__ico-plus"></i><i class="fas fa-minus top-nav__ico-minus"></i></span>
            </li>

            <li class="top-nav__item-level-1 last menu-item p-1336">
              <a href="/families/"> Families</a>
              <span class="top-nav__submenu-button "><i class="fas fa-plus top-nav__ico-plus"></i><i class="fas fa-minus top-nav__ico-minus"></i></span>
            </li>

            <li class="top-nav__item-level-1 menu-item p-1091">
              <a href="/programming/jobs/"> Jobs</a>
              <span class="top-nav__submenu-button "><i class="fas fa-plus top-nav__ico-plus"></i><i class="fas fa-minus top-nav__ico-minus"></i></span>
            </li>
        </ul>
    </div>
    <!-- /.menus -->

    <div class="menu-cross-links">
      <span class="menu-cross-links__title"><a href="tel:1-347-878-2431"><i class="fas fa-phone"></i> 347-878-2431</a> </span>
      <!-- <a class="crosslink programming" href="<?= $pages->get('1051')->url ?>">mainstages Programming</a>
      <a class="crosslink families" href="<?= $pages->get('1336')->url ?>">mainstages for Families</a> -->
    </div>
    <!-- /.menu-cross-links -->

  </div>
  <!-- /.main-menu-wrapper -->

  

</nav>
<!-- /.top-nav -->

<a class="header__menu-trigger">
  <span class="label">Menu</span>
  <div class="header__menu-icon"> 
    <div class="header__menu-icon__middle"></div>
  </div>
  <!-- /.header__menu-icon -->
</a> <!-- /.header__menu-menu-trigger -->
