  <script>var base_href = '/';</script>
	<script type="text/javascript" src="<?= $config->urls->templates ?>js/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>	
	<script type="text/javascript" src="<?= $config->urls->templates ?>js/plugins.js"></script>		
	<script src="<?= $config->urls->templates ?>js/map-style.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCTRSHf8sjMCfK9PHPJxjJkwrCIo5asIzE"></script>	
	<script type="text/javascript" src="<?= $config->urls->templates ?>js/scripts.js"></script>
	<script type="text/javascript" src="<?= $config->urls->templates ?>js/custom.js"></script>
	<!-- <script type="text/javascript" src="<?= $config->urls->templates ?>js/jquery.pixlayout.min.js"></script>	 -->