<div class="footer__wrapper">
    <footer class="footer">
      <div class="footer__inner-wrapper">
        
        <div class="footer__social-media">
          <a href="https://www.facebook.com/mainstages" target="_blank"><i class="fab fa-facebook-f"></i></a>
          <a href="https://twitter.com/mainstages" target="_blank"><i class="fab fa-twitter"></i></a>
          <a href="https://www.instagram.com/mainstages/" target="_blank"><i class="fab fa-instagram"></i></a>
          <a href="https://www.youtube.com/user/mainstages" target="_blank"><i class="fab fa-youtube"></i></a>
          
        </div>
        <!-- /.footer__social-media -->

        <div class="footer__logos">
          <a href="http://www.nystea.org/" class="footer__logo-link"><img src="<?= $config->urls->templates ?>assets/images/nystea-logo.png" alt="Mainstages Logo"></a>
          <a href="http://mainstages.com/" class="footer__logo-link"><img src="<?= $config->urls->templates ?>assets/images/mainstages-logo-classic.png" alt="Mainstages Logo"></a>
        </div>

        <div class="footer__row">

          <div class="footer__column footer__column--1">
            <div class="adr">
              <div class="street-address">21-33 29th. Avenue - Suite 2</div>
              <div>
                <span class="locality">Astoria</span>, <span class="region" title="New York">NY</span> 
                <span class="postal-code"> 11102</span>
              </div>
              <div class="country-name">USA</div>
            </div>
          </div>
          
          <div class="footer__column footer__column--2">
            <div>Phone: <a class="tel" href="tel:+1-347-878-2431">347-878-2431</a></span></div>
            <div>Email: <a href="mailto:support@mainstages.com" class="email">support@mainstages.com</a></div>
          </div>
        </div>

        <p class="footer__copyright">Copyright &copy;<?= date("Y") ?> Mainstages. All Rights Reserved | Website by <a href="http://ovswebsites.com/">OVS Websites</a></p>
      </div>
      <!-- /.footer__inner-wrapper -->
    </footer>
    </div>
    <!-- /.footer__wrapper -->