<head>
    <?php require($config->paths->templates.'includes/head-common.inc'); ?>

      <link rel="stylesheet" href="<?= $config->urls->templates?>assets/styles/vendor/pretty-checkbox.min.css" />
      <link rel="stylesheet" href="<?= $config->urls->templates?>assets/styles/vendor/fa-svg-with-js.css" />
      <link rel="stylesheet" href="<?= $config->urls->templates?>assets/styles/styles-performances.css" />

  </head>