  <section id="special-offer">
    <div class="container">
      <div class="item">
        <h3>Request Our Services</h3>
        <h2 class="no-bg">Get in touch now</h2>
        <p>Fill in the form below and we will get back to you ASAP.<br>You can also give us a call at <strong><a href="tel:6029563844">(602) 956 3844</a></strong>.</p>
        
        <div class="cognito">
        <script src="https://services.cognitoforms.com/s/xPoircp7HEGoNo_tpFEirg"></script>
        <script>Cognito.load("forms", { id: "141" });</script>
        </div>
        
        <img src="<?= $config->urls->templates ?>images/_pest-control-guy.png" alt="Special" class="large">
      </div>
    </div>
  </section>