<div id="get-discount">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 inner">
          <div class="row">
            <div class="col-lg-3 col-md-4 percent">-30%</div>
            <div class="col-lg-6 col-md-5 txt">
              <span class="white">Our New</span>
              <span class="black">Guaranteed Bed Bug Services</span>
            </div>
            <div class="col-lg-3 col-md-3">
              <a href="#" class="btn btn-white btn-md">Get Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>