<div id="countUp">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-ms-6 center-flex">
        <span class="pointText">Family Owned</span>
        <p>&amp; Operated</p>
      </div>
      <div class="col-md-3 col-sm-6 col-ms-6 center-flex">
        <span class="pointText">Environ-<br>mentally</span>
        <p>responsible</p>
      </div>
      <div class="col-md-3 col-sm-6 col-ms-6 center-flex">
        <span class="pointText">Licensed</span>
        <!--  id="countUp-3" -->
        <p>&amp; Insured</p>
      </div>
      <div class="col-md-3 col-sm-6 col-ms-6 center-flex">
        <span class="pointText">Servicing <br> Arizona</span>
        <p><a href="#" class="btn btn-xs btn-black-bordered" style="margin-bottom:0">See Map</a></p>
      </div>
    </div>
  </div>