  <section id="slider-full" class="slider-full" data-zs-bullets="true" data-zs-speed="22000" data-zs-interval="10000" data-zs-switchSpeed="400" data-zs-src='["<?= $config->urls->templates ?>images/_slider-1.jpg","<?= $config->urls->templates ?>images/_slider-2.jpg"]' data-zs-overlay="false">
    <div class="container">
        <h1><span class="green">We Kill</span> <span>Weeds &amp; Pests</span> <span>Anywhere</span></h1>
        <a href="#" class="btn btn-green btn-white-hover">About us</a>
        <!-- About -->
    </div>
  </section>