  <section id="design-project">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-sm-12">
						<div class=" block-left matchHeight">
							<h2 class="no-bg"><span class="white">Top of the line</span> Weed &amp; Pest Services</h2>
							<p>Has your yard been infiltrated by weeds that you can't get rid of? Has your home been invaded by unwanted, unsanitary visitors?</p>
							<h3 style="margin-top:0;color:white;">Get help!</h3>
							<p>Don't fight the good fight alone - call Custom Weed &amp; Pest Control.
							We kill weeds and pests and guarantee the results. 
							If the weeds or pests come back, so will we-free of charge.
							</p>
							<!-- <a href="#" class="btn btn-green btn-white-hover black btn-xs btn-md-mob">get now</a> -->
						</div>
						<div class="divider"></div>
					</div>
					<div class="col-md-6 col-sm-12">
						<div class=" block-right matchHeight"></div>
					</div>
				</div>
			</div>
    </section>	