<header class="page-header" style="background-image: url(<?= $config->urls->templates ?>images/_inner-bg.jpg); background-size: cover;">
  <div class="container">
    
    <h1><?= $page->get("long_title|title") ?></h1>
    <ol class="bread">
      <li>
          <a href="index.html"><span>Home</span></a>
      </li>
      <li class="divider"><span>|</span></li>
      <li>
          <span>Flowers Planting</span>
      </li>
    </ol>
  </div>
</header>