<section id="projects">
			<div class="container">
				<h2><span class="black">Completed</span> Projects</h2>

				<div class="btns slider-filter">
					<a href="#" class="btn btn-xs btn-white-green btn-active" data-filter="">All</a>
					<a href="#" class="btn btn-xs btn-white-green" data-filter="1">Design</a>
					<a href="#" class="btn btn-xs btn-white-green" data-filter="2">Gardering</a>
					<a href="#" class="btn btn-xs btn-white-green" data-filter="3">Flowers planting</a>
					<a href="#" class="btn btn-xs btn-white-green" data-filter="4">Sowing grass</a>
				</div>

				<div class="row items">
					<div class="swiper-container slider-filter-container" id="project-slider">
						<div class="swiper-wrapper">
														<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-2">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-1.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-4">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-2.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Landscape Design<br> of Wooden House</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-1">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-3.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Design and Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-1">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-1.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-2.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Landscape Design<br> of Wooden House</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-3.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Design and Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-1">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-1.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-1">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-2.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Landscape Design<br> of Wooden House</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-3.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Design and Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-1.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-4">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-2.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Landscape Design<br> of Wooden House</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-1">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-3.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Design and Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-2">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-1.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-2.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Landscape Design<br> of Wooden House</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-2">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-3.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Design and Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-1.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-3">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-2.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Landscape Design<br> of Wooden House</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>
							<div class="col-md-4 col-ms-6 swiper-slide filter-item filter-type-4">
								<div class="item">
									<img src="<?= $config->urls->templates ?>images/_project-3.jpg" class="full-width" alt="Project">
									<div class="info">
										<div class="overlay">
											<h3>Design and Gardening<br> of Private Cottage</h3>
											<div>
												<p>Quisque commodo sit amet eros et maximus. Nullam sed vehicula ante. </p>
												<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer rutrum malesuada fermentum. </p>
											</div>
										</div>										
										<a href="#" class="btn btn-green btn-white-hover black btn-xs">view</a>
									</div>
								</div>
							</div>						</div>
						<div class="navigation">
							<a href="#" class="arrow-left fa fa-chevron-left"></a>
							<a href="#" class="arrow-right fa fa-chevron-right"></a>
						</div>
					</div>
				</div>
			</div>
		</section>