<section id="gardeners">
    <div class="container">	
      <div class="row">
        <div class="col-md-3 txt">
          <h3><span class="black">Our Best</span><br> <span class="white">Gardeners</span></h3>
          <ul class="check checked-white">
            <li>Quisque commodo</li>
            <li>Sit amet eros et maximus</li>
            <li>Nullam sed vehicula ante</li>
            <li>Vestibulum ante ipsum</li>
            <li>Primis in faucibus orci luctus</li>
            <li>Ultrices posuere cubilia </li>
          </ul>
          <a href="#" class="btn btn-black btn-white-hover btn-md hidden-sm hidden-ms hidden-xs">View All</a>
        </div>
        <div class="col-md-3 col-sm-4">
          <div class="item">
            <span class="label-white">Best</span>
            <img src="<?= $config->urls->templates ?>images/_best-1.png" class="full-width" alt="Best">
            <h5>Maria Garcia</h5>
            <p>landscape designer</p>
            <ul class="social social-small">
              <li><a href="#" class="fa fa-twitter"></a></li>
              <li><a href="#" class="fa fa-facebook"></a></li>
              <li><a href="#" class="fa fa-instagram"></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-4">
          <div class="item">
            <span class="label-white">Best</span>
            <img src="<?= $config->urls->templates ?>images/_best-2.png" class="full-width" alt="Best">
            <h5>Carolina Weiss</h5>
            <p>landscape designer</p>
            <ul class="social social-small">
              <li><a href="#" class="fa fa-twitter"></a></li>
              <li><a href="#" class="fa fa-facebook"></a></li>
              <li><a href="#" class="fa fa-instagram"></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-4">
          <div class="item">
            <span class="label-white">Best</span>
            <img src="<?= $config->urls->templates ?>images/_best-3.png" class="full-width" alt="Best">
            <h5>Monica petersson</h5>
            <p>landscape designer</p>
            <ul class="social social-small">
              <li><a href="#" class="fa fa-twitter"></a></li>
              <li><a href="#" class="fa fa-facebook"></a></li>
              <li><a href="#" class="fa fa-instagram"></a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-12 btns hidden-lg hidden-md">
          <a href="#" class="btn btn-black btn-white-hover btn-md">View All</a>
        </div>
      </div>
    </div>
  </section>